# Generated by Django 2.0.8 on 2018-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='/img/icone_vazio.png', upload_to='', verbose_name='Foto de Perfil'),
        ),
    ]
